export { default as Home } from './Home.jsx'
export { default as Orders } from './Orders.jsx'
export { default as Auth } from './Auth.jsx'
export { default as About } from './About.jsx'
export { default as Contact } from './Contact.jsx'